apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-api-deployment
  labels:
    app: ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
      - name: ai-api
        image: urfucourses/ai_api_demo_app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-api-service
spec:
  type: NodePort
  selector:
    app: ai-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
